# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 5) do

  create_table "dns_records", :force => true do |t|
    t.column "dns_zone_id", :integer,                                 :null => false
    t.column "host",        :string,                 :default => "@", :null => false
    t.column "ttl",         :integer,                :default => 180, :null => false
    t.column "type",        :string,   :limit => 10, :default => "",  :null => false
    t.column "mx_priority", :string,   :limit => 10
    t.column "data",        :string,                 :default => "",  :null => false
    t.column "created_at",  :datetime,                                :null => false
    t.column "updated_at",  :datetime,                                :null => false
    t.column "query_count", :integer,  :limit => 32
  end

  create_table "dns_tlds", :force => true do |t|
  end

  create_table "dns_zones", :force => true do |t|
    t.column "dns_tld_id",  :integer,                                              :null => false
    t.column "name",        :string,                :default => "",                :null => false
    t.column "comment",     :text
    t.column "primary_ns",  :string,                :default => "",                :null => false
    t.column "resp_person", :string,                :default => "root.localhost.", :null => false
    t.column "serial",      :integer, :limit => 20, :default => 0,                 :null => false
    t.column "refresh",     :integer,               :default => 28800,             :null => false
    t.column "retry",       :integer,               :default => 14400,             :null => false
    t.column "expire",      :integer,               :default => 604800,            :null => false
    t.column "minimum",     :integer,               :default => 86400,             :null => false
  end

  create_table "zone_transfers", :force => true do |t|
    t.column "dns_zone_id", :integer, :null => false
    t.column "client",      :text
  end

end
